---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-pinfish-analysis"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "Workspaces"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-pinfish-analysis.git"

## Pipeline-specific parameters:

# Input genome
genome_fasta: "Homo_sapiens.GRCh38.dna.primary_assembly.fa"

# cDNA or direct RNA reads in fastq format
reads_fastq: "reads.fastq"

# Extra option passed to minimap2 when generating index
minimap_index_opts: "-k14"

# Extra options passed to minimap2
minimap2_opts: "-uf"
# Enable this for SIRV data:
#minimap2_opts: "--splice-flank=no"

# Minmum mapping quality
minimum_mapping_quality: 10

# Options passed to spliced_bam2gff
spliced_bam2gff_opts: "-s"

# Minimum cluster size
minimum_cluster_size: 10

# Minimum isoform percent
minimum_isoform_percent: 1.0

# Internal exon boundary tolerance
exon_boundary_tolerance: 10

# Terminal exon boundary tolerance
terminal_exon_boundary_tolerance: 30

# Extra minimap2 options for mapping polished reads
minimap2_opts_polished: "-uf"
# Enable this for SIRV data:
#minimap2_opts_polished: "--splice-flank=no"

# Options passed to spliced_bam2gff when converting alignments of polished reads
spliced_bam2gff_opts_pol: "-s"

# Options passed to collapse_partials when collapsing fragmentation artifacts
# in clustered and polished transcripts.

# Internal exon boundary tolerance for collapsing
collapse_internal_tol: 5

# Five prime boundary tolerance for collapsing
collapse_five_tol: 5000

# Three prime boundary tolerance for collapsing
collapse_three_tol: 30

# Threads
threads: 50


